language: node_js
node_js: '12'
cache: npm
install:
  - npm install
before_script:
  - npm install -g gatsby-cli
script: 
  - gatsby build
after_success:
- find public -type f -exec curl --verbose --progress-bar --ipv4 --connect-timeout 8 --max-time 120 --retry 128 --disable-epsv --ftp-pasv -u "${FTP_USER}:${FTP_PASSWORD}" --ftp-create-dirs -T {} ftp://s71.linuxpl.com/public_html/\{\} \;