name: Build gatsby site

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x

      - name: Yarn cache
        uses: actions/cache@v2.1.0
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Gatsby Cache Folder
        uses: actions/cache@v2.1.0
        id: gatsby-cache-folder
        with:
          path: .cache
          key: ${{ runner.os }}-cache-gatsby
          restore-keys: |
            ${{ runner.os }}-cache-gatsby

      - name: Gatsby Public Folder
        uses: actions/cache@v2.1.0
        id: gatsby-public-folder
        with:
          path: public/
          key: ${{ runner.os }}-public-gatsby
          restore-keys: |
            ${{ runner.os }}-public-gatsby

      
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
        
      - name: Setup env variables and build gatsby site
        run: yarn build
        env:
          API_DATO_CMS: ${{ secrets.API_DATO_CMS }}
          TRACKING_ID: ${{ secrets.TRACKING_ID }}
          
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://s71.linuxpl.com/public_html/
          ftp-username: ${{ secrets.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public
          git-ftp-args: --all

      - name: DatoCMS notifications (success)
        if: ${{ failure() }}
        run: |
          curl -n -X POST https://webhooks.datocms.com/bd48c298f03e6769bc47/deploy-results \
            -H 'Content-Type: application/json' \
            -d '{ "status": "error" }'
      
      - name: DatoCMS notifications (success)
        if: ${{ success() }}
        run: |
          curl -n -X POST https://webhooks.datocms.com/bd48c298f03e6769bc47/deploy-results \
          -H 'Content-Type: application/json' \
          -d '{ "status": "success" }'
